async function main() {}

main().catch((error) => {
	console.error(`error: ${error}`);

	process.exit(1);
});
